import { auth, signOut } from '@/auth'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Document } from './document'
import './globals.css'
import { Login } from './login'
import { Revalidator } from './revalidator'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  if (!session) {
    return (
      <Document>
        <div className="w-screen h-screen grid place-items-center">
          <Login />
        </div>
      </Document>
    )
  }

  return (
    <Document>
      <Revalidator>
        <div className="flex gap-4">
          <Link className="text-blue-600 underline" href="/">
            Index
          </Link>
          <Link className="text-blue-600 underline" href="/foo">
            Foo
          </Link>
        </div>

        <hr />

        <div className="flex gap-4">
          <p>Signed in as {session.user.email}</p>
          <form
            action={async () => {
              'use server'
              await signOut()
            }}
          >
            <button type="submit">Sign Out</button>
          </form>
        </div>

        <hr />

        {children}
      </Revalidator>
    </Document>
  )
}
